"""Add depreciation fields to Asset

Revision ID: 7cf99ae46379
Revises: d27d1bb77e1d
Create Date: 2025-07-04 17:32:31.436042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf99ae46379'
down_revision = 'd27d1bb77e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('salvage_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('useful_life', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('useful_life')
        batch_op.drop_column('salvage_value')
        batch_op.drop_column('purchase_cost')

    # ### end Alembic commands ###
