"""Add disposal tracking to Asset

Revision ID: d27d1bb77e1d
Revises: a16017d7bf2f
Create Date: 2025-07-04 12:36:45.040582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27d1bb77e1d'
down_revision = 'a16017d7bf2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disposal_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('disposal_method', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_disposed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('is_disposed')
        batch_op.drop_column('disposal_method')
        batch_op.drop_column('disposal_reason')

    # ### end Alembic commands ###
